### ISSUE TITLE
电量显示有点问题

### ISSUE THREAD

**Issue by viosonlee** [lgs3137/MR_S1-macOS#1]
概率性出现电池电量不动的情况，卡在某一个值。指纹不知道是不是不能使用；触摸板目前3指以上好像是没有效果

**Comment by lgs3137** [comment]
①电池电量卡某个值我暂时没有遇到（需要日志）
②指纹暂时不可用
③触摸板多手势需要配置驱动实现，系统设置里面的触摸板设置是不行的，可参考http://bbs.pcbeta.com/viewthread-1782490-1-1.html 这里的教程改

**Comment by viosonlee** [comment]
电量卡在某个地方的情况,重建一下缓存就好了,现在已经用了好几个月了,很感谢
