### ISSUE TITLE
觉得耗电好快啊

### ISSUE THREAD

**Issue by qaqslzy** [lgs3137/MR_S1-macOS#10]
i5独显版的
在60％左右的时候，两分钟左右就掉百分之一的电，新电脑，电还没有充过一次循环，这样正常吗？

**Comment by lgs3137** [comment]
新机建议先在win下使用电池用完一次，再充满测试（主要是校准电池数据）
我自己的也是i5独显版本，暂时没发现你的问题

**Comment by wyzrec** [comment]
@lgs3137 想问下你的机器在满电的情况下大概能用多久..
