### ISSUE TITLE
新驱动没有办法双击拖拽和两指右键了

### ISSUE THREAD

**Issue by qaqslzy** [lgs3137/MR_S1-macOS#11]
有办法可以改吗？

**Comment by qaqslzy** [comment]
哦……右键是被我在设置里面改了……但是双击拖拽我没有找到……

**Comment by lgs3137** [comment]
因使用了万能驱动，触摸板大部分功能无法定义（可自行修改源码编译或改修按键映射），其中：
单指轻触代表点击、双指轻触代表右键等功能可在 设置-触摸板 中自行设置。
具体可以直接参考驱动作者文档：https://github.com/RehabMan/OS-X-Voodoo-PS2-Controller
三指上下左右滑动分别映射了ALT+↑  ALT+↓  ALT+←  ALT+→  可以在
VoodooPS2Controller.kext/Contents/PlugIns/VoodooPS2Keyboard.kext/Contents/Info.plist 中修改触发按键定义。
`
<key>ActionSwipeDown</key>
<string>67 d, 67 u</string>
<key>ActionSwipeLeft</key>
<string>3b d, 7b d, 7b u, 3b u</string>
<key>ActionSwipeRight</key>
<string>3b d, 7c d, 7c u, 3b u</string>
<key>ActionSwipeUp</key>
<string>3b d, 7e d, 7e u, 3b u</string>
`
注意其中的值 “3b d, 7e d, 7e u, 3b u”形式表示了分别同时按下编码为 “3b 7e”的按键，然后同时松开两个个键。
