### ISSUE TITLE
电池供电下，电脑睡眠时间长后，蓝牙睡眠唤醒后失效

### ISSUE THREAD

**Issue by NatureProtect** [lgs3137/MR_S1-macOS#12]
不知道大佬是否有同样的遭遇，在接通电源的情况下，蓝牙可正常的睡眠唤醒，当切换到电池供电后，蓝牙在长期睡眠后无法唤醒，WiFi可以正常唤醒。
蓝牙用的是自己换的BCM94352Z
电脑型号为 机械革命S1 i7-8550U顶配版
已尝试过将文件BrcmFirmwareData.kext和BrcmPatchRAM2.kext和AirportBrcmFixup.kext复制到/Library/Extensions目录下，未解决问题。求大佬指教一二

**Comment by lgs3137** [comment]
没试过，晚上再回去测试一下

**Comment by lgs3137** [comment]
将文件BrcmFirmwareData.kext和BrcmPatchRAM2.kext和AirportBrcmFixup.kext复制到/Library/Extensions目录下，即可解决睡眠唤醒后可能引起的蓝牙失效的问题。
当然，在重启前，还要重建一下系统的缓存，命令为：（也可以使用Kext Utility重建缓存）

 #!/bin/sh
sudo chmod -Rf 755 /S*/L*/E*
sudo chown -Rf 0:0 /S*/L*/E*
sudo chmod -Rf 755 /L*/E*
sudo chown -Rf 0:0 /L*/E*
sudo rm -Rf /S*/L*/PrelinkedKernels/*
sudo rm -Rf /S*/L*/Caches/com.apple.kext.caches/*
sudo touch -f /S*/L*/E*
sudo touch -f /L*/E*
sudo kextcache -Boot -U /
