### ISSUE TITLE
大佬，appstore不能登陆，没有以太网卡

### ISSUE THREAD

**Issue by logonod** [lgs3137/MR_S1-macOS#14]
大佬，更新了最新的BCM94352z分支，wifi正常，但是没有以太网卡，appstore不能登陆

**Comment by lgs3137** [comment]
我这边正常，NullEthernet.kext虚拟有线网卡驱动也正常，是否尝试过重建缓存？

**Comment by logonod** [comment]
重建过 可还是不行 系统报告里显示这台电脑似乎没有安装任何 PCI 以太网卡。 wifi显示en2

**Comment by lgs3137** [comment]
好的，晚上我再回去测试下

**Comment by lgs3137** [comment]
![image](https://user-images.githubusercontent.com/1278141/55325957-22bceb00-54b9-11e9-8b12-e4cb8ff6f95a.png)
你好，我这边使用最新的BCM94352z分支重建缓存重启已经无法重现你的问题，建议可以尝试先把你的 EFI/Clover删除再重新下载并重建缓存（另外，如果需要登录 FaceTime 等建议使用工具随机生成新的设备串号修改config.plist）
