### ISSUE TITLE
触摸板手势无效

### ISSUE THREAD

**Issue by hoffmannchen** [lgs3137/MR_S1-macOS#18]
你好，我用黑果的系统安装后用你的EFI替换，现在基本正常。但是触摸板手势一直不行，显示找不到触控板。还有亮度调节一开始是可以后来又突然不行了。除了替换efi还需要什么其他步骤吗？

**Comment by hoffmannchen** [comment]
i5集显版，用的是10.14最终版。

**Comment by ghost** [comment]
我也是 应该就是不能驱动

**Comment by lgs3137** [comment]
的确是最新适配 10.15 的 VoodooPS2Controller.kext 在低版本中存在触摸板无法使用,我在最新的提交已经切换到稳定版的 VoodooPS2Controller.kext 修复了这个问题.
目前我已经重装回 10.14.5 测试正常, Releases中的 EFI.zip 后面我再重新传一个.

**Comment by lgs3137** [comment]
@hoffmannchen 建议直接下载最新分支安装.
先把原来的 EFI 备份好,然后删除 EFI 下的 BOOT / CLOVER 两个文件夹,再解压下载回来的 EFI ,最后强烈建议使用 Kext Uitility 重新缓存一次.
