### ISSUE TITLE
有三个问题请教一下

### ISSUE THREAD

**Issue by skywalker512** [lgs3137/MR_S1-macOS#2]
####  1 请问您的WiFi安装好没？

因为主板是倒装，自己从来没有拆机的经验，请问WiFi好更换吗？

--------
 因为自己从来没有在笔记本上安装黑苹果，上次安装(台式机)还是东皇和道奇兔的10.6时代**原谅我的伸手党**
####  3 请问风扇运行正常吗？

**Comment by lgs3137** [comment]
1.已经安装了 BCM94352Z WiFi在背部，只需要拆下D面后盖即可更换。
2.理论上 i7 版本一样可以使用的，变频无需单独调整
3.风扇转速正常，功耗/发热/噪音均比Win下面好很多（我自己使用这样子）
