### ISSUE TITLE
请问触摸板能使用三指拖动手势吗？

### ISSUE THREAD

**Issue by aliyoge** [lgs3137/MR_S1-macOS#21]
如题。。。

**Comment by lgs3137** [comment]
![image](https://user-images.githubusercontent.com/1278141/59925148-0605d300-946a-11e9-8a80-e3ee74803200.png)

不是很明白你所说的三指拖动手势具体是什么?如图这里的话部分可以用,部分不行.
再说了这个机子的触摸板尺寸两个手指放上去几乎就不用移动了...

**Comment by linziwen** [comment]
这个三指拖动我暂时发现有两种玩法，一种是楼主截图的出调度的，另外一种是system preferences->accessibility->mouse & trackpad->trackpad options->可以设置three finger drag
不过这样以后三指向上就不会出调度了。
