### ISSUE TITLE
请问关于hdmi合盖后进入睡眠的问题

### ISSUE THREAD

**Issue by linziwen** [lgs3137/MR_S1-macOS#22]
你好，请问一下我在display设置里面无论选extend还是mirror，可以成功把显示投到外接显示器上面。不过当我合上笔记本盖子以后就进入睡眠状态，同时显示器也没有信号了。电源设置里面好像也没找到合上盖子这一动作的配置。

**Comment by lgs3137** [comment]
![image](https://user-images.githubusercontent.com/1278141/59976759-5c564b80-95fb-11e9-82ee-3fb55e2db368.png)

设置合盖不休眠需要使用 [InsomniaX](https://pan.baidu.com/s/1miHQ23Q) 第三方软件实现。

**Comment by linziwen** [comment]
感谢楼主指导。
还有一个反馈一下，我发现原来插上电源合盖也不会进入睡眠。而没有插上电源合盖就会睡眠。
问题解决，关闭issue。
