### ISSUE TITLE
历史版本下载问题

### ISSUE THREAD

**Issue by tamen2** [lgs3137/MR_S1-macOS#23]
使用的是10.14.5，想要下载2019.06.04的BCM94352z版本，百度等多番尝试后没有成功。
求大佬和各位朋友们帮帮小弟。

**Comment by lgs3137** [comment]
![image](https://user-images.githubusercontent.com/1278141/60754531-e3042300-a014-11e9-90ad-2854aebafb22.png)

你好，首先如图确认下你BCM94352z的产品 ID:0xe07a 是否如图跟我的一样属于联想版，才能直接使用我的驱动文件。如果一样请直接使用最新分支下的完整Clover即可（目前最新分支的驱动都是完整支持10.15 d3、10.14.5的），我的机子就是用最新分支的Clover在10.14.5下正常运行。
测试蓝牙可正常可连接天猫方糖、普通蓝牙小音箱、蓝牙耳机、蓝牙鼠标、小米9、iPad Air。

**Comment by lgs3137** [comment]
当然如果你就想要下载2019.06.04的BCM94352z版本的话可以直接点击下面这个链接下载即可。
https://github.com/lgs3137/MR_S1-macOS/tree/8ad398b5805efb63956910cbcbc625e1e1daeff1

**Comment by tamen2** [comment]
谢谢大佬，问题已经解决。之所以需要旧版本是因为10.14.5系统使用新版efi后导致的cpu温度居高不下，经过多次重建缓存和多次重启后还是没有解决。关机出去吃个小龙虾后再开机居然好了。谢谢大佬的解答，祝大佬工作顺利

**Comment by tamen2** [comment]
另外，我把oc文件夹给删掉后高温问题才解决，或许是我操作不对吧

**Comment by lgs3137** [comment]
@tamen2 目前OC的确不能有效加载CPUFriend驱动导致CPU长期处于高频状态导致高温。不过你只要不用OC启动应该正常的。既然问题解决了就好~

**Comment by ChenZesen** [comment]
> @tamen2 目前OC的确不能有效加载CPUFriend驱动导致CPU长期处于高频状态导致高温。不过你只要不用OC启动应该正常的。既然问题解决了就好~

那么大佬，现在这个OC问题解决了没

**Comment by lgs3137** [comment]
@ChenZesen 这个问题需要等待OC更新
