### ISSUE TITLE
大佬bios怎么设置

### ISSUE THREAD

**Issue by ChenZesen** [lgs3137/MR_S1-macOS#24]

**Comment by lgs3137** [comment]
这款机子BIOS不需要特别设置也没有什么能设置的，默认的就行。。。
通电狂按 F2 进入 BIOS，F10 进入引导列表

**Comment by lgs3137** [comment]
唯一要设置的就关闭安全引导（不关闭这个就只能引导Windows系统），另外最好只开启仅UEFI引导模式
