### ISSUE TITLE
DW1820A bluetooth

### ISSUE THREAD

**Issue by Cyl3el2Cleal2** [lgs3137/MR_S1-macOS#26]
How to install bluetooth kext for BCM2045A0
OS: 10.15 Catalina
WIFI card: DW1820A

![image](https://user-images.githubusercontent.com/38637268/66461586-8dbc2f80-eaa3-11e9-8749-17e14cdc37d3.png)

**Comment by lgs3137** [comment]
Sorry, I don't have DW1820A. I suggest you follow the driver method here.(BTW,macOS DW1820A works normally, there may still be unknown problems.)
https://blog.daliansky.net/DW1820A_BCM94350ZAE-driver-inserts-the-correct-posture.html

Modify `config.plist` and add the [DW1820A driver files](http://7.daliansky.net/DW1820A/BT_for_DW1820A_Ver.2.zip) to `/EFI/CLOVER/kexts/Other`

```
        <key>Boot</key>
	<dict>
		<key>Arguments</key>
		<string>brcmfx-driver=1 brcmfx-country=#a</string>
	</dict>
	<key>Devices</key>
	<dict>
		<key>Properties</key>
		<dict>
			<key>PciRoot(0x0)/Pci(0x1c,0x3)/Pci(0x0,0x0)</key>
			<dict>
				<key>AAPL,slot-name</key>
				<string>WLAN</string>
				<key>compatible</key>
				<string>pci14e4,4353</string>
				<key>device_type</key>
				<string>Airport Extreme</string>
				<key>model</key>
				<string>DW1820A (BCM4350) 802.11ac Wireless</string>
				<key>name</key>
				<string>Airport</string>
			</dict>
		</dict>
	</dict>
```

[DW1820A_config.plist.zip](https://github.com/lgs3137/MR_S1-macOS/files/3706247/DW1820A_config.plist.zip)

**Comment by Cyl3el2Cleal2** [comment]
Thank you. It works.
