### ISSUE TITLE
High cpu temperatures

### ISSUE THREAD

**Issue by abdullah-abunada** [lgs3137/MR_S1-macOS#27]
Hello,

Thank you for amazing effort, but I have issue when I working on several programs the cpu temperatures to 75 c.

Do you have any idea to solve this issue?

Best

**Comment by lgs3137** [comment]
I suggest you can try to use the Activity Monitor to find too many CPU-intensive processes, ensuring that some application bugs or system initialization are not caused.
Then try to force the end of the abnormal process, if you have replaced the hardware, Shutdown and remove AC power, press the "rest" of the back the hole.
BTW, macOS temperature on this machine is indeed higher than Windows.

**Comment by abdullah-abunada** [comment]
thank you for your informations.
