### ISSUE TITLE
笔记本在不接电源的情况下，睡眠久了（一晚上）就自动关机，早上起来开盖就需要重开机了，求大佬改进

### ISSUE THREAD

**Issue by NatureProtect** [lgs3137/MR_S1-macOS#30]

**Comment by lgs3137** [comment]
有空我重现下看看，需要报错日志才能确认问题

**Comment by lgs3137** [comment]
奇怪，昨晚我就尝试了，只使用电池自动睡眠，早上唤醒完全正常。。。
我是最新分支的OC引导，10.15.2系统下测试的，你可以重现下问题，如果kernel panic的话再次正常启动会有系统报错信息的，请提供详细的报错信息，另外可以加群反馈

**Comment by NatureProtect** [comment]
好的 我加群去聊

**Comment by qaqslzy** [comment]
俺也一样。。系统版本10.14.3

**Comment by qaqslzy** [comment]
我在V2EX上 [https://www.v2ex.com/t/397727](url) 看到了如下的解决方案。
```
sudo pmset -a standby 0
```
在将standby关掉之后，确实没有再发现合盖之后再自动关机的情况了。不过这样好像会导致没有办法通过硬盘睡眠？

讨论中还提到 `sudo pmset -a autopoweroff 0` 但是我在 `pmset -g` 中没有找到这个参数，不知道这句话还是否有作用。
