### ISSUE TITLE
App Store not working

### ISSUE THREAD

**Issue by abdullah-abunada** [lgs3137/MR_S1-macOS#31]
Hello,
Thank you for effort, but after latest updates the app store not working correctly, its entered in resign-in loop.

**Comment by lgs3137** [comment]
![image](https://user-images.githubusercontent.com/1278141/73626603-7de4de80-4684-11ea-9e4d-fef70a121955.png)
My App Store is working. Are you currently booting with Clover or OC? 
Please try to logout AppleID and then restart your computer to login again.

**Comment by abdullah-abunada** [comment]
when I rollback to first EFI file, it's work fine, but when I move to new version of EFI it's entered in sign-in loop when Installing or updating apps

**Comment by abdullah-abunada** [comment]
it works after last updates, thanks
