### ISSUE TITLE
how to use the MSIECcontrol

### ISSUE THREAD

**Issue by Apoliphene** [lgs3137/MR_S1-macOS#32]
i updated the newest efi folder but i can not find where the msieccontrol file mentioned in readme is.

**Comment by lgs3137** [comment]
https://github.com/lgs3137/MR_S1-macOS/blob/master/MSIECControl
```
MSIECControl 0 30 50 60 80 100
```

**Comment by Apoliphene** [comment]
> https://github.com/lgs3137/MR_S1-macOS/blob/master/MSIECControl
> 
> ```
> MSIECControl 0 30 50 60 80 100
> ```
 So cloud you tell me how to open or install this file? I cannot open this with test editor or other apps. pls. I am just a user not a programmer. Thanks for your reply.

**Comment by lgs3137** [comment]
![image](https://user-images.githubusercontent.com/1278141/74084222-08c04180-4aa8-11ea-814d-94ad1541f6e0.png)

Use the latest EFI, then open the terminal.app and move MSIECControl to the terminal window, then enter 6 parameters (0 ~ 100)

**Comment by lgs3137** [comment]
Failure after restart or sleep.
