### ISSUE TITLE
视频播放问题

### ISSUE THREAD

**Issue by matchch** [lgs3137/MR_S1-macOS#33]
Clover和OC均测试，测试环境为最新edge和chrome
机型为S1-02
edge和chrome开启硬件加速和HIDPI情况下，播放youtube 1080P及以上视频全屏会闪屏，不清楚是否HIDPI的问题
腾讯视频客户端部分视频会错误码: 200.301001.-11800，可以使用冰雪奇缘2进行测试，网页无影响

以上均可复现成功

**Comment by lgs3137** [comment]
我这没有开启HiDPI，Chrome开启硬件加速，测试1080P全屏播放正常，建议你关闭HiDPI后再测试看看效果，如果是开启HiDPI导致的暂时没有办法解决，毕竟这个HiDPI是伪装分辨率实现的

**Comment by matchch** [comment]
已关闭HIDPI，还是一样，准备先更换彼岸花的看看情况，确定是否EFI问题

**Comment by matchch** [comment]
更换彼岸花Clover，情况还是一样，难道又是1820A的锅...

**Comment by matchch** [comment]
已经解决，原因是BIOS内设置的显存(256M)过大，设置为128M正常

**Comment by matchch** [comment]
腾讯视频的是DRM问题，核显无法解决
