### ISSUE TITLE
App Store无法下载

### ISSUE THREAD

**Issue by qaqslzy** [lgs3137/MR_S1-macOS#35]
![image](https://user-images.githubusercontent.com/31992368/76929031-14f8b380-691e-11ea-8868-964d47902066.png)
在之前的EFI中是可以下载的，在更新了最新的EFI后出现了这个问题。

**Comment by qaqslzy** [comment]
切换到旧的EFI后可以下载

**Comment by abdullah-abunada** [comment]
Yes, like me this issue rised when I replaced the old EFI wih new version.

**Comment by qaqslzy** [comment]
> Yes, like me this issue rised when I replaced the old EFI wih new version.

Did you solve this problem? I saw you said on other issues that it works now.

**Comment by qaqslzy** [comment]
@abdullah-abunada 

Did you solve this problem? I saw you said on other issues that it works now.

**Comment by abdullah-abunada** [comment]
Not yet, when I restored the patched file from old EFI, it's worked. but when I installed the last one the problem comes back.
Finally, when you want to install anything from the App Store, you should restore old EFI *_*.

**Comment by lgs3137** [comment]
EFI/CLOVER/config.plist
```
<key>BoardSerialNumber</key>
<string>C02938306GUHWVPUE</string>
key>SerialNumber</key>
<string>C02ZFNZGHV29</string>
<key>SmUUID</key>
<string>D161ADAD-9AC7-49B3-B4F9-0F5D11A0FF35</string>
```
This bug is so amazing. I asked many people in the QQ group that everything is normal. 
What wireless network card do you use? And you rebuild SerialNumber, BoardSerialNumber, SmUUID?

**Comment by abdullah-abunada** [comment]
I'm using a Tplink wifi card, and I didn't rebuild any things, just keep it as normal.

**Comment by qaqslzy** [comment]
To use iMessage I use SerialNumber, BoardSerialNumber, SmUUID from my friends MacBook pro (or without SerialNumber?). Ande My wireless network card I think that is DW1560, remember not too clear.

**Comment by abdullah-abunada** [comment]
You can close this issue, its solved by generate new serial number using OCC. @lgs3137, @qaqslzy
