### ISSUE TITLE
cant turn off bluetooth

### ISSUE THREAD

**Issue by abdullah-abunada** [lgs3137/MR_S1-macOS#37]
After the last update, the turns off button is disabled and I can't turn it off, any advice?

![Screen Shot 2020-07-21 at 7 53 59 PM](https://user-images.githubusercontent.com/1808834/88083615-f6385100-cb8b-11ea-9f80-8335fc7f5eb2.png)

**Comment by lgs3137** [comment]
is 1820A?

**Comment by lgs3137** [comment]
if 1820A, you can try this one and reset nvram.
[EFI_1820A_20200721.zip](https://github.com/lgs3137/MR_S1-macOS/files/4956842/EFI_1820A_20200721.zip)

**Comment by abdullah-abunada** [comment]
How I can reset the nvram using OC boot?

**Comment by lgs3137** [comment]
Press the space key on the OC boot options interface, and select Reset NVRAM.

**Comment by abdullah-abunada** [comment]
Unfortunately, the same issue :(

**Comment by abdullah-abunada** [comment]
I fixed it, by downloading OCC then add the bluetooth kext to config file manually and enable it.
