### ISSUE TITLE
Msi ps42 8ra

### ISSUE THREAD

**Issue by constantineoo** [lgs3137/MR_S1-macOS#39]
Hi Master,

I have configuration:

i5 8265U
16GB RAM 
Ssd: samsung 970 evo plus nvme
intel HD 620
Nvidia mx 250 - not work i know
Network: Intel Wireless AC 9560

could you make me an EFI for openCore 0.6.4 final Big sur.  I will be very grateful

Thank you

**Comment by constantineoo** [comment]
Thanks for the updates! I am asking for a link dmg image of Big Sur. I don't know Chinese and it's very difficult for me.

I have one more question.  I downloaded EFI to EFI dmg catalina.  I set everything up in bios.  when the bootloader starts and I turn on the catalin installation, the apple logo appears on 2sec and restarts.

**Comment by lgs3137** [comment]
You can try this script to download the macOS Big Sur system image.
https://github.com/corpnewt/gibMacOS
Your notebook is quite different from mine, you can only use it as a reference.
Now you can try my modified EFI, it is not guaranteed to work properly.
(Cannot upload a single large file) You need to download three files, then modify the file name, delete the last .zip and make sure that the three file names as
`
EFI_PS42_8RA.zip.001
`
`
EFI_PS42_8RA.zip.002
`
`
EFI_PS42_8RA.zip.003
`
then unzip EFI_PS42_8RA.zip.001 normally.

[EFI_PS42_8RA.zip.001.zip](https://github.com/lgs3137/MR_S1-macOS/files/5577616/EFI_PS42_8RA.zip.001.zip)
[EFI_PS42_8RA.zip.002.zip](https://github.com/lgs3137/MR_S1-macOS/files/5577618/EFI_PS42_8RA.zip.002.zip)
[EFI_PS42_8RA.zip.003.zip](https://github.com/lgs3137/MR_S1-macOS/files/5577619/EFI_PS42_8RA.zip.003.zip)

**Comment by constantineoo** [comment]
Your package has a file error and cannot be extracted
error: EFI/OC/KEXTS/Airportltwm.kext/contents/macos/airportltlwm

**Comment by constantineoo** [comment]
Dude i love you!!! it works but I have a problem with the keyboard and touchpad doesn't work and keyboard doesn't work and touchpad.

I have one last question besides the keyboard and touchpad.  is it safe to use this hack?  do I have to generate my own serial number in the opencore cofiguration file

**Comment by lgs3137** [comment]
Download the keyboard and touchpad driver file and unzip `ApplePS2SmartTouchPad.kext.zip` the driver files in the `\EFI\OC\Kexts` directory and then reboot.
[ApplePS2SmartTouchPad.kext.zip](https://github.com/lgs3137/MR_S1-macOS/files/5578754/ApplePS2SmartTouchPad.kext.zip)

To modify your own serial number, please refer to the picture to modify three places in the `\EFI\OC\config.plist` file.
(be careful not to break the format.)

![image](https://user-images.githubusercontent.com/1278141/99891475-13e60600-2ca5-11eb-8b3e-e3acc353d6b5.png)

**Comment by constantineoo** [comment]
Thank you very much once again. I've been testing the third day and working very well.

**Comment by lgs3137** [comment]
You can try this EFI, which is adapted by friends in our group who have the same configuration as `MSI PS42 8RA`
https://github.com/JokerAB/Mechrevo-S1-Hackintosh

**Comment by constantineoo** [comment]
Honestly, your EFI is better and lighter and it works stably. After uploading the new system, it was recognizable better, but it is not stable. The processor has a stuttering difference in operation. Thank you very much for your help. I think some settings can be downloaded from the new one, but based on your EFI.

**Comment by constantineoo** [comment]
how to reset nvram in openCore?

**Comment by lgs3137** [comment]
press the space bar in the OpenCore boot menu.

**Comment by constantineoo** [comment]
you think it's worth making a Bios patch for macOs big sur? Is it worth doing?

**Comment by lgs3137** [comment]
if you have time and interest,why not?
of course changing the BIOS is risky.
