### ISSUE TITLE
大佬能做一个macOS Mojave 10.14的EFI吗？

### ISSUE THREAD

**Issue by tamen2** [lgs3137/MR_S1-macOS#4]
10.13.4换了dw1560网卡后非常完美，日常使用感觉比Windows省电。非常感谢大佬的付出！不过希望大佬有闲心做一下macOS Mojave 10.14的EFI啦~感谢大佬！

**Comment by lgs3137** [comment]
这周有点儿忙，十一期间更新

**Comment by tamen2** [comment]
哈哈哈，感谢大佬

**Comment by sonadd** [comment]
期待大佬的mojave EFI！！！

**Comment by lgs3137** [comment]
实在不好意思，这个假期就休了3天都在加班。。。只能后面空点我再看看了。

**Comment by lgs3137** [comment]
已经更新Clover
