### ISSUE TITLE
USB接口变为内建

### ISSUE THREAD

**Issue by matchch** [lgs3137/MR_S1-macOS#40]
在目前最新的EFI(2020.12.2)下，两个USB接口均为内建，导致移动硬盘插入后识别为USB内建磁盘，无法弹出，但查看SSDT-USB.aml写的也没问题，均为3
自行注入也失效
后续加入USBInjectAll.kext后正常
查看commit记录发现在https://github.com/lgs3137/MR_S1-macOS/commit/bd2550605e45c7109f6e03d2bc1210a891ea2fc8 中删除

**Comment by lgs3137** [comment]
主要还是OC支持的USB ACPI方法有调整，下次更新修复

**Comment by lgs3137** [comment]
已修复
