### ISSUE TITLE
大佬的10.14EFI国庆期间能发么？

### ISSUE THREAD

**Issue by sonadd** [lgs3137/MR_S1-macOS#5]
换上DW1560后，High Sierra的EFI升到10.13.6非常完美，然后在Mojave发布后开始学着折腾，能搜到的hotpatch教程特别是对萌新友好一点的着实太少，在黑果小兵EFI的基础上尝试hotpatch后花屏。。。。。。
只能寄希望于大佬了。
还有一个使用xzhih/one-key-hidpi后的bug，就是开机第一次休眠唤醒后会有分辨率错误，再次及多次休眠唤醒错误消失，大佬知道原因吗？

**Comment by sonadd** [comment]
原来是clover bootLoader版本过低导致花屏

**Comment by tamen2** [comment]
你的efi好用吗？在大佬更新之前分享出来用用呗~手痒了~~~

**Comment by sonadd** [comment]
> 你的efi好用吗？在大佬更新之前分享出来用用呗手痒了

也是边学边做，快收尾了，目前就差一个亮度调节快捷键问题，弄好了分享给你。

**Comment by lgs3137** [comment]
实在不好意思，这个假期就休了3天都在加班。。。只能后面空点我再看看了。

**Comment by tamen2** [comment]
感谢大佬，感谢分享的朋友~

**Comment by sonadd** [comment]
在大佬原版的基础上更新了BootLoader、kext以及各种补丁（主要是核显的驱动方式变动很大），目前没有发现bug，有问题可以反馈
[https://github.com/sonadd/MR_S1-macOS-Mojave]

**Comment by tamen2** [comment]
辛苦了，明天开工~~这个是换了dw1560网卡的efi吗？如果不是后面的朋友们需要自己替换~

**Comment by sonadd** [comment]
> 辛苦了，明天开工~~这个是换了dw1560网卡的EFI吗？如果不是后面的朋友们需要自己替换〜

是换了1560后的，由于误删了两个kextstopatch导致Fn+上下键不能调节亮度，已重新上传CLOVER

**Comment by lgs3137** [comment]
已经更新Clover
