### ISSUE TITLE
连接hdmi笔记本的屏幕闪烁，显示器正常。

### ISSUE THREAD

**Issue by YogaXiong1** [lgs3137/MR_S1-macOS#9]
型号：i5-8250u 集显版

**Comment by lgs3137** [comment]
暂时没有外接显示器测试。。。
已更新Clover，可尝试使用最新的

**Comment by ghost** [comment]
一样 闪烁

**Comment by lgs3137** [comment]
@cwr31 我暂时没有 HDMI 设备测试,可以尝试把 笔记本合盖约五秒后再开盖  看看能不能临时解决

**Comment by ghost** [comment]
> @cwr31 我暂时没有 HDMI 设备测试,可以尝试把 笔记本合盖约五秒后再开盖 看看能不能临时解决

可以解决 关上再开 一秒钟就好了 谢谢大佬

**Comment by lgs3137** [comment]
@YogaXiong1 @cwr31 最新版本的驱动应该是修复了外接 HDMI 显示器开机无法启动以及接入 HDMI 后内屏需要盒盖的问题，有条件的童鞋可以更新测试下效果 。
